[package]
name = "mquickjs-rs"
version = "0.1.0"
edition = "2021"

[features]
default = []
ridl-extensions = ["dep:ridl_registry"]

[dependencies]
libc = "0.2"
mquickjs-sys = { path = "../mquickjs-sys" }
ridl_registry = { path = "../../ridl-modules/registry", optional = true }

[build-dependencies]
bindgen = "0.72"
cc = "1.0"