[package]
name = "stdlib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
mquickjs-rs = { path = "../../../deps/mquickjs-rs", features = ["ridl-extensions"] }
libc = "0.2"