[package]
name = "test_class"
version = "0.1.0"
edition = "2024"

[dependencies]
mquickjs-rs = { path = "../../deps/mquickjs-rs", features = ["ridl-extensions"] }

[build-dependencies]
ridl-tool = { path = "../../deps/ridl-tool" }

[lib]
crate-type = ["rlib"]
